# Generated by Django 5.1.3 on 2024-11-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockquote",
            name="volume_weighted_average",
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
