# Generated by Django 5.1.2 on 2024-10-16 19:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0002_company_active_stockquote"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stockquote",
            unique_together={("company", "time")},
        ),
    ]
