# Generated by Django 5.1.3 on 2024-11-08 00:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0003_alter_stockquote_managers"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stockquote",
            unique_together={("company", "time")},
        ),
    ]
